### ISSUE TITLE
cancel fire animation if player has full nether armor

### ISSUE THREAD

**Issue by 4ceRT4in** [4ceRT4in/TitanReborn#72]

**Comment by Globox1997** [comment]
done

**Comment by 4ceRT4in** [comment]
Now there is no fire animation at all
The Animation should only be canceled if the player wears a full net (4 pieces) of nether armor. 
Otherwise (no armor, 3 pieces or less) the animation is still shown
